export enum UserActionConstants {
	USER_VERIFY_TOKEN = 'User: VERIFY_TOKEN',
	USER_VERIFY_TOKEN__COMPLETE = 'User: VERIFY_TOKEN__COMPLETE',
	USER_VERIFY_TOKEN__FAILED = 'User: VERIFY_TOKEN__FAILED'
}
