export enum UserActionConstants {
	VERIFY_USER_TOKEN = 'User: VERIFY_TOKEN',
	VERIFY_USER_TOKEN__COMPLETE = 'User: VERIFY_TOKEN__COMPLETE',
	VERIFY_USER_TOKEN__FAILED = 'User: VERIFY_TOKEN__FAILED'
}
