export enum ModifiedDataActionConstants {
	MODIFIEDDATA_CHANGE_CONTENT = 'Modified data: CHANGE_CONTENT',
	MODIFIEDDATA_CHANGE_HEADER_TITLE = 'Modified data: CHANGE_HEADER_TITLE',
	MODIFIEDDATA_DELETE_COLUMN = 'Modified data: DELETE_COLUMN',
	MODIFIEDDATA_DELETE_ROW = 'Modified data: DELETE_ROW'
}
