export enum ModifiedDataActionConstants {
	MODIFIEDDATA_LOAD_DATA = 'Modified data: LOAD_DATA',
	MODIFIEDDATA_CHANGE_CONTENT = 'Modified data: CHANGE_CONTENT',
	MODIFIEDDATA_CHANGE_HEADER_TITLE = 'Modified data: CHANGE_HEADER_TITLE',
	MODIFIEDDATA_DELETE_COLUMN = 'Modified data: DELETE_COLUMN',
	MODIFIEDDATA_DELETE_ROW = 'Modified data: DELETE_ROW',
	MODIFIEDDATA_LOAD_DATA__COMPLETE = 'Modified data: LOAD_DATA__COMPLETE',
	MODIFIEDDATA_LOAD_DATA__FAILED = 'Modified data: LOAD_DATA__FAILED'
}
