export enum ProjectsActionConstants {
	LOAD_PROJECTS = 'Projects: LOAD',
	LOAD_PROJECTS__COMPLETE = 'Projects: LOAD__COMPLETE',
	LOAD_PROJECTS__FAILED = 'Projects: LOAD__FAILED',

	CREATE_DRAFT_PROJECT = 'Project: CREATE_DRAFT',
	CREATE_DRAFT_PROJECT__COMPLETE = 'Project: CREATE_DRAFT__COMPLETE',
	CREATE_DRAFT_PROJECT__FAILED = 'Project: CREATE_DRAFT__FAILED',

	LOAD_ONE_PROJECT = 'Projects: LOAD_ONE',
	LOAD_ONE_PROJECT__COMPLETE = 'Projects: LOAD_ONE__COMPLETE',
	LOAD_ONE_PROJECT__FAILED = 'Projects: LOAD_ONE__FAILED',
	CHANGE_PROJECT_NAME = 'Project: CHANGE_NAME',

	REMOVE_PAGE_PROJECT = 'Project: REMOVE_PAGE_PROJECT',

	REMOVE_CHART_PROJECT = 'Project: REMOVE_CHART_PROJECT',
	REMOVE_CHART_PROJECT__COMPLETE = 'Project: REMOVE_CHART_PROJECT__COMPLETE',
	REMOVE_CHART_PROJECT__FAILED = 'Project: REMOVE_CHART_PROJECT__FAILED',

	REMOVE_DATASET_PROJECT = 'Project: REMOVE_DATASET_PROJECT',

	SAVE_PROJECT = 'Projects: SAVE',
	SAVE_PROJECT__COMPLETE = 'Projects: SAVE__COMPLETE',
	UPDATE_PROJECT__COMPLETE = 'Projects: UPDATE_PROJECT__COMPLETE',
	SAVE_PROJECT__FAILED = 'Projects: SAVE__FAILED',

	LOAD_PROJECTS_INFO = 'Projects: LOAD_PROJECTS_INFO',
	LOAD_PROJECTS_INFO__COMPLETE = 'Projects: LOAD_PROJECTS_INFO__COMPLETE',
	LOAD_PROJECTS_INFO__FAILED = 'Projects: LOAD_PROJECTS_INFO__FAILED',

	SHARE_PROJECT = 'Projects: SHARE_PROJECT',
	SHARE_PROJECTS__COMPLETE = 'Projects: SHARE_PROJECTS__COMPLETE',
	SHARE_PROJECTS__FAILED = 'Projects: SHARE_PROJECTS__FAILED',

	DELETE_ONE_PROJECT = 'Projects: DELETE_ONE_PROJECT',
	DELETE_ONE_PROJECT__COMPLETE = 'Projects: DELETE_ONE_PROJECT__COMPLETE',
	DELETE_ONE_PROJECT__FAILED = 'Projects: DELETE_ONE_PROJECT__FAILED',

	UPDATE_PROJECT_NAME = 'Projects: UPDATE_PROJECT_NAME',
	UPDATE_PROJECT_NAME__COMPLETE = 'Projects: UPDATE_PROJECT_NAME__COMPLETE',
	UPDATE_PROJECT_NAME__FAILED = 'Projects: UPDATE_PROJECT_NAME__FAILED'
}
