export enum ProjectsActionConstants {
	LOAD_PROJECTS = 'Projects: LOAD',
	LOAD_PROJECTS__COMPLETE = 'Projects: LOAD__COMPLETE',
	LOAD_PROJECTS__FAILED = 'Projects: LOAD__FAILED',

	CREATE_DRAFT_PROJECT = 'Project: CREATE_DRAFT',
	CREATE_DRAFT_PROJECT__COMPLETE = 'Project: CREATE_DRAFT__COMPLETE',
	CREATE_DRAFT_PROJECT__FAILED = 'Project: CREATE_DRAFT__FAILED',

	LOAD_ONE_PROJECT = 'Projects: LOAD_ONE',
	LOAD_ONE_PROJECT__COMPLETE = 'Projects: LOAD_ONE__COMPLETE',
	LOAD_ONE_PROJECT__FAILED = 'Projects: LOAD_ONE__FAILED',
	CHANGE_PROJECT_NAME = 'Project: CHANGE_NAME',

	SAVE_PROJECT = 'Projects: SAVE',
	SAVE_PROJECT__COMPLETE = 'Projects: SAVE__COMPLETE',
	UPDATE_PROJECT__COMPLETE = 'Projects: UPDATE_PROJECT__COMPLETE',
	SAVE_PROJECT__FAILED = 'Projects: SAVE__FAILED'
}
