export enum ChartsActionConstants {
	SELECT_CHART = 'Charts: SELECT_CHART',
	SELECT_CHART__COMPLETE = 'Charts: SELECT_CHART__COMPLETE',
	SELECT_CHART__FAILED = 'Charts: SELECT_CHART__FAILED',
	CREATE_CHART = 'Charts: CREATE_CHART',
	CREATE_CHART__COMPLETE = 'Charts: CREATE_CHART__COMPLETE',

	LOAD_CHARTS = 'Charts: LOAD',
	LOAD_CHARTS__COMPLETE = 'Charts: LOAD__COMPLETE',
	LOAD_CHARTS__FAILED = 'Charts: LOAD__FAILED'
}
