export enum ChartsActionConstants {
	SELECT_CHART = 'Charts: SELECT_CHART',
	SELECT_CHART__COMPLETE = 'Charts: SELECT_CHART__COMPLETE',
	SELECT_CHART__FAILED = 'Charts: SELECT_CHART__FAILED',

	SET_DIMENSION = 'Charts: SET_DIMENSION',
	REMOVE_DIMENSION = 'Charts: REMOVE_DIMENSION',

	REMOVE_ALL_DIMENSION = 'Charts: REMOVE_ALL_DIMENSION',

	CHANGE_CUSTOM_SETTINGS = 'Charts: CHANGE_CUSTOM_SETTINGS',

	CREATE_CHART = 'Charts: CREATE_CHART',
	CREATE_CHART__COMPLETE = 'Charts: CREATE_CHART__COMPLETE',
	CREATE_CHART__FAILED = 'Charts: CREATE_CHART__FAILED',

	PICK_ACTIVE_CHART = 'Charts: PICK_ACTIVE_CHART',

	SET_DATASET_CHART = 'Charts: SET_DATASET_CHART',

	LOAD_CHARTS = 'Charts: LOAD',
	LOAD_CHARTS__COMPLETE = 'Charts: LOAD__COMPLETE',
	LOAD_CHARTS__FAILED = 'Charts: LOAD__FAILED'
}
